In [2]:
!pip install sklearn

  Using cached sklearn-0.0-py2.py3-none-any.whl
  Using cached scikit_learn-0.24.2-cp38-cp38-win_amd64.whl (6.9 MB)
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
  Using cached threadpoolctl-2.2.0-py3-none-any.whl (12 kB)


In [3]:
import pandas as pd
import numpy as np
import tensorflow as tf

# from keras.utils.np_utils import to_categorical
from sklearn.linear_model import LinearRegression

In [4]:
df = pd.read_csv('data.csv', sep=';')
df.head()

year     team  standing
0  2015  Arsenal         3
1  2016  Arsenal         2
2  2017  Arsenal         5
3  2018  Arsenal         6
4  2019  Arsenal         5

In [23]:
vals = df.values
sequences = 2
teams = np.unique(df['team'].values)
print(teams)
X = []
y = []
X_test = []
X_test_teams = []


df_dummies = pd.get_dummies(df, columns=['team'])
df_filtered = df_dummies.drop(columns=['year'])

for team in teams:
    df_team = df_filtered.loc[df['team'] == team]
    #print(df_team)
    team_standings = df_team.values
    # print(f"len(team_standings) {len(team_standings)}")
    for i in range(0, len(team_standings)):
        # print(f"team {team} {i}th year")
        if i + sequences < len(team_standings):
            x_values = team_standings[i:i+sequences]
            #print(x_values)
            X.append(x_values)
            y_value = team_standings[i+sequences, 0]
            #print(y_value)
            y.append(y_value)
        elif i + sequences == len(team_standings):
            x_values = team_standings[i:i+sequences]
            X_test.append(x_values)
            print(f"team {team}")
            X_test_teams.append(team)

X = np.array(X)
y = np.array(y)
X_test = np.array(X_test)
print(X.shape)
print(y.shape)
print(X_test.shape)

['Arsenal' 'Aston Villa' 'Bournemouth' 'Brighton' 'Burnley' 'Cardiff City'
 'Chelsea' 'Crystal Palace' 'Everton' 'Fulham' 'Huddersfield' 'Hull City'
 'Leeds United' 'Leicester City' 'Liverpool' 'Man City' 'Man United'
 'Middlesbrough' 'Newcastle' 'Norwich City' 'Sheffiel United'
 'Southampton' 'Stoke City' 'Sunderland' 'Swansea' 'Tottenham' 'Watford'
 'West Brom' 'West Ham' 'Wolves']
team Arsenal
team Aston Villa
team Bournemouth
team Brighton
team Burnley
team Cardiff City
team Chelsea
team Crystal Palace
team Everton
team Fulham
team Huddersfield
team Hull City
team Leeds United
team Leicester City
team Liverpool
team Man City
team Man United
team Newcastle
team Norwich City
team Sheffiel United
team Southampton
team Stoke City
team Sunderland
team Swansea
team Tottenham
team Watford
team West Brom
team West Ham
team Wolves
(138, 2, 31)
(138,)
(29, 2, 31)


In [24]:
print(y)

[ 5  6  5  8  8 21 21 21 17 11  9 12 21 14 18 21 21 15 17 15 16 16  7 15
 10 17 18  1  5  3  4  4 14 11 12 14 14  7  8  8 12 10 21 19 21 18 21 16
 20 21 21 18 21 21 21 21 21 21 21 21  9 12  9 21  9  5  5  4  4  2  1  3
  3  1  1  2  1  6  2  6  3  2 10 13 13 12 21 21 21 20 21 21 21 21  9 20
  8 17 16 11 15 13 19 21 21 21 21 20 21 21 21 21 15 18  2  3  4  6  7 14
 11 19 21 10 20 21 21 19 11 13 10 16  6 21 21  7  7 13]


In [25]:
print(X_test)

[[[ 8  1  0 ...  0  0  0]
  [ 8  1  0 ...  0  0  0]]

 [[17  0  1 ...  0  0  0]
  [11  0  1 ...  0  0  0]]

 [[18  0  0 ...  0  0  0]
  [21  0  0 ...  0  0  0]]

 ...

 [[21  0  0 ...  1  0  0]
  [19  0  0 ...  1  0  0]]

 [[16  0  0 ...  0  1  0]
  [ 6  0  0 ...  0  1  0]]

 [[ 7  0  0 ...  0  0  1]
  [13  0  0 ...  0  0  1]]]


In [8]:
def linear_transform(X):
    if len(X.shape) == 3:
        if X.shape[1] == 1:
            X_linear = np.squeeze(X, 1)
        else:
            X_linear = X.reshape((X.shape[0], X.shape[1]* X.shape[2]))
    return X_linear

In [32]:
X_linear = linear_transform(X)
print(X_linear.shape)

(109, 93)


In [33]:
print(X_linear.shape)
print(y.shape)
reg = LinearRegression().fit(X_linear, y)
reg.score(X_linear, y)

(109, 93)
(109,)


0.8300872005581456

In [34]:
X_test_linear = linear_transform(X_test)
print(X_test_linear.shape)

(29, 93)


In [35]:
print(X_test_teams)

['Arsenal', 'Aston Villa', 'Bournemouth', 'Brighton', 'Burnley', 'Cardiff City', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Huddersfield', 'Hull City', 'Leeds United', 'Leicester City', 'Liverpool', 'Man City', 'Man United', 'Newcastle', 'Norwich City', 'Sheffiel United', 'Southampton', 'Stoke City', 'Sunderland', 'Swansea', 'Tottenham', 'Watford', 'West Brom', 'West Ham', 'Wolves']


In [36]:
result = reg.predict(X_test_linear)
print(np.array(result))

[ 6.21426392e+00  1.76158142e+01  1.72249756e+01  1.65786438e+01
  1.27881165e+01 -1.99919023e+11  4.32546997e+00  1.27546692e+01
  9.44900513e+00  1.97068787e+01  1.93099060e+01  2.06166687e+01
  1.80753479e+01  1.08146362e+01  3.54293823e+00  1.59689331e+00
  3.05270386e+00  1.30103455e+01  2.06907654e+01  1.87936096e+01
  1.34379272e+01  1.87740479e+01  2.03648987e+01  1.68785095e+01
  4.60598755e+00  1.72952881e+01  1.84105530e+01  1.09422302e+01
  1.58688049e+01]


In [38]:
inds = np.argsort(result, axis=0)
print(inds)

[ 5 15 16 14  6 24  0  8 13 27  7  4 17 20 28  3 23  2 25  1 12 26 21 19
 10  9 22 11 18]


In [39]:
for i, ind in enumerate(inds):
    team = X_test_teams[ind]
    res = result[ind]
    print(f"{i+1}th team {team} is {round(res, 2)}")

1th team Cardiff City is -199919022819.06
2th team Man City is 1.6
3th team Man United is 3.05
4th team Liverpool is 3.54
5th team Chelsea is 4.33
6th team Tottenham is 4.61
7th team Arsenal is 6.21
8th team Everton is 9.45
9th team Leicester City is 10.81
10th team West Ham is 10.94
11th team Crystal Palace is 12.75
12th team Burnley is 12.79
13th team Newcastle is 13.01
14th team Southampton is 13.44
15th team Wolves is 15.87
16th team Brighton is 16.58
17th team Swansea is 16.88
18th team Bournemouth is 17.22
19th team Watford is 17.3
20th team Aston Villa is 17.62
21th team Leeds United is 18.08
22th team West Brom is 18.41
23th team Stoke City is 18.77
24th team Sheffiel United is 18.79
25th team Huddersfield is 19.31
26th team Fulham is 19.71
27th team Sunderland is 20.36
28th team Hull City is 20.62
29th team Norwich City is 20.69


# LSTM

In [26]:
import tensorflow as tf
from tensorflow.keras.layers import LSTM, Dropout, Dense
from tensorflow.keras import Sequential

In [78]:

def set_dataset(X, y):
    train_ds = tf.data.Dataset.from_tensor_slices((X, y))
    return train_ds

In [122]:
def preprocessing(df, sequences):
    vals = df.values
    teams = np.unique(df['team'].values)
    print(teams)
    X = []
    y = []
    X_test = []
    X_test_teams = []

    df_dummies = pd.get_dummies(df, columns=['team'])
    df_filtered = df_dummies.drop(columns=['year'])

    for team in teams:
        df_team = df_filtered.loc[df['team'] == team]
        #print(df_team)
        team_standings = df_team.values
        # print(f"len(team_standings) {len(team_standings)}")
        for i in range(0, len(team_standings)):
            # print(f"team {team} {i}th year")
            if i + sequences < len(team_standings):
                x_values = team_standings[i:i+sequences]
                #print(x_values)
                X.append(x_values)
                y_value = team_standings[i+sequences, 0]
                #print(y_value)
                y.append(y_value)
            elif i + sequences == len(team_standings):
                x_values = team_standings[i:i+sequences]
                X_test.append(x_values)
                print(f"team {team}")
                X_test_teams.append(team)

    X = np.array(X)
    y = np.array(y)
    X_test = np.array(X_test)
    print(X.shape)
    print(y.shape)
    print(X_test.shape)
    return X, y, X_test, X_test_teams

In [131]:
def set_lstm(n_timesteps, n_features, hidden, n_outputs):
    model = Sequential()
    model.add(LSTM(hidden, input_shape=(n_timesteps, n_features)))
    model.add(Dropout(0.1))
    #model.add(Dense(hidden, activation='relu'))
    model.add(Dense(n_outputs, activation='relu'))
    # model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['mse'])
    model.compile(loss='mse', optimizer='adam', metrics=['mse'])
    model.summary()
    return model

def predict(model, X_test):
    lstm_preds = model.predict(X_test)
    inds = np.argsort(lstm_preds[:,0])
    print(inds)
    print(lstm_preds.shape)

    for i, ind in enumerate(inds):
        team = X_test_teams[ind]
        pred = lstm_preds[ind, 0]
        print(f"{i+1}th team {team} is {str(np.round(pred, 1))}")

def train(n_timesteps, n_features, hidden, output_size, batch_size, epochs):
    model = set_lstm(n_timesteps, n_features, hidden, output_size)
    # Compile the model
    # optimizer = tf.keras.optimizers.Adam()
    # model.compile(optimizer=optimizer, loss='mse')

    # train_ds = set_dataset(X, y)
    print(X.shape)
    X_train, X_val = X[:100,:,:], X[100:,:]
    y_train, y_val = y[:100], y[100:]

    model.fit(X, y, epochs=epochs, batch_size=batch_size, verbose=2, validation_split=0.2)
    # evaluate model
    _, accuracy = model.evaluate(X_val, y_val, batch_size=batch_size, verbose=0)

    print(accuracy)
    return model

In [139]:
n_timesteps = 3
n_features = 31
hidden = 64
output_size = 1  # labels are from 1-21
batch_size = 4
epochs = 100

X, y, X_test, X_test_teams = preprocessing(df, n_timesteps)

model = train(n_timesteps, n_features, hidden, output_size, batch_size, epochs)


['Arsenal' 'Aston Villa' 'Bournemouth' 'Brighton' 'Burnley' 'Cardiff City'
 'Chelsea' 'Crystal Palace' 'Everton' 'Fulham' 'Huddersfield' 'Hull City'
 'Leeds United' 'Leicester City' 'Liverpool' 'Man City' 'Man United'
 'Middlesbrough' 'Newcastle' 'Norwich City' 'Sheffiel United'
 'Southampton' 'Stoke City' 'Sunderland' 'Swansea' 'Tottenham' 'Watford'
 'West Brom' 'West Ham' 'Wolves']
team Arsenal
team Aston Villa
team Bournemouth
team Brighton
team Burnley
team Cardiff City
team Chelsea
team Crystal Palace
team Everton
team Fulham
team Huddersfield
team Hull City
team Leeds United
team Leicester City
team Liverpool
team Man City
team Man United
team Newcastle
team Norwich City
team Sheffiel United
team Southampton
team Stoke City
team Sunderland
team Swansea
team Tottenham
team Watford
team West Brom
team West Ham
team Wolves
(109, 3, 31)
(109,)
(29, 3, 31)
Model: "sequential_61"
_________________________________________________________________
Layer (type)                 Output Shape

Epoch 72/100
22/22 - 0s - loss: 7.1232 - mse: 7.1232 - val_loss: 22.1893 - val_mse: 22.1893
Epoch 73/100
22/22 - 0s - loss: 7.6491 - mse: 7.6491 - val_loss: 21.9048 - val_mse: 21.9048
Epoch 74/100
22/22 - 0s - loss: 7.4800 - mse: 7.4800 - val_loss: 22.7116 - val_mse: 22.7116
Epoch 75/100
22/22 - 0s - loss: 7.2940 - mse: 7.2940 - val_loss: 21.4726 - val_mse: 21.4726
Epoch 76/100
22/22 - 0s - loss: 7.5785 - mse: 7.5785 - val_loss: 23.0770 - val_mse: 23.0770
Epoch 77/100
22/22 - 0s - loss: 7.1273 - mse: 7.1273 - val_loss: 22.4754 - val_mse: 22.4754
Epoch 78/100
22/22 - 0s - loss: 6.5161 - mse: 6.5161 - val_loss: 22.1265 - val_mse: 22.1265
Epoch 79/100
22/22 - 0s - loss: 6.3457 - mse: 6.3457 - val_loss: 23.0133 - val_mse: 23.0133
Epoch 80/100
22/22 - 0s - loss: 6.4883 - mse: 6.4883 - val_loss: 21.7585 - val_mse: 21.7585
Epoch 81/100
22/22 - 0s - loss: 6.2578 - mse: 6.2578 - val_loss: 21.9529 - val_mse: 21.9529
Epoch 82/100
22/22 - 0s - loss: 6.5425 - mse: 6.5425 - val_loss: 22.4822 - val_m

In [140]:
predict(model, X_test)

[15 14 16  6 13  0  8 27  4 24  1  7 17 12 28  5 25 23 26  3 20  2 19  9
 10 21 22 18 11]
(29, 1)
1th team Man City is 0.9
2th team Liverpool is 1.3
3th team Man United is 3.2
4th team Chelsea is 3.5
5th team Leicester City is 5.1
6th team Arsenal is 8.4
7th team Everton is 9.5
8th team West Ham is 9.8
9th team Burnley is 11.4
10th team Tottenham is 11.9
11th team Aston Villa is 11.9
12th team Crystal Palace is 11.9
13th team Newcastle is 12.2
14th team Leeds United is 12.5
15th team Wolves is 13.8
16th team Cardiff City is 14.0
17th team Watford is 14.3
18th team Swansea is 14.5
19th team West Brom is 14.6
20th team Brighton is 15.2
21th team Southampton is 15.5
22th team Bournemouth is 17.3
23th team Sheffiel United is 18.7
24th team Fulham is 19.1
25th team Huddersfield is 19.7
26th team Stoke City is 20.5
27th team Sunderland is 20.7
28th team Norwich City is 20.8
29th team Hull City is 20.9
